[project]
name = "cmc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "paramiko>=3.5.1",
    "pyinstaller>=6.14.2",
    "python-dotenv>=1.1.1",
    "tqdm>=4.67.1",
]
